#!/bin/bash

# 0.5 cMpc/h rare-peak quick scout: z=49 initial stage.
# MUSIC writes a DM-only 64^3 HDF5 unigrid; AREPO splits it into
# 64^3 gas + 64^3 Type-1 DM particles at startup.

SELFGRAVITY
HIERARCHICAL_GRAVITY
CELL_CENTER_GRAVITY
ALLOW_DIRECT_SUMMATION
DIRECT_SUMMATION_THRESHOLD=500
PMGRID=64
RCUT=5.0

NSOFTTYPES=2
MULTIPLE_NODE_SOFTENING
ADAPTIVE_HYDRO_SOFTENING
TREE_BASED_TIMESTEPS

REGULARIZE_MESH_CM_DRIFT
REGULARIZE_MESH_CM_DRIFT_USE_SOUNDSPEED

DOUBLEPRECISION=1
DOUBLEPRECISION_FFTW
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_COORDINATES_IN_DOUBLEPRECISION
NGB_TREE_DOUBLEPRECISION

HAVE_HDF5
COOLING

BLACKHOLE_FFR
BH_FFR_SEED_ONLY_MOST_MASSIVE
BH_FFR_SEED_MAX_REDSHIFT=22

FOF
FOF_PRIMARY_LINK_TYPES=2
FOF_SECONDARY_LINK_TYPES=1+32

GENERATE_GAS_IN_ICS

PROCESS_TIMES_OF_OUTPUTLIST
REDUCE_FLUSH
