#!/bin/bash

# Post-split cosmological executable for z<=22 snapshots that already contain
# gas.  It deliberately omits GENERATE_GAS_IN_ICS.

SELFGRAVITY
HIERARCHICAL_GRAVITY
CELL_CENTER_GRAVITY
ALLOW_DIRECT_SUMMATION
DIRECT_SUMMATION_THRESHOLD=500
PMGRID=128
RCUT=5.0

NSOFTTYPES=2
MULTIPLE_NODE_SOFTENING
ADAPTIVE_HYDRO_SOFTENING
TREE_BASED_TIMESTEPS

REGULARIZE_MESH_CM_DRIFT
REGULARIZE_MESH_CM_DRIFT_USE_SOUNDSPEED

DOUBLEPRECISION=1
DOUBLEPRECISION_FFTW
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_COORDINATES_IN_DOUBLEPRECISION
NGB_TREE_DOUBLEPRECISION

HAVE_HDF5
COOLING

BLACKHOLE_FFR
BH_FFR_SEED_ONLY_MOST_MASSIVE
BH_FFR_SEED_MAX_REDSHIFT=22

FOF
FOF_PRIMARY_LINK_TYPES=2
FOF_SECONDARY_LINK_TYPES=1+32

PROCESS_TIMES_OF_OUTPUTLIST
REDUCE_FLUSH
