#!/bin/bash

# 0.5 cMpc/h rare-peak cosmology: z=99 initial stage.
# MUSIC writes a DM-only 128^3 HDF5 unigrid; AREPO splits it into
# 128^3 gas + 128^3 Type-1 DM particles at startup.

SELFGRAVITY
PMGRID=128
RCUT=5.0

NSOFTTYPES=2
MULTIPLE_NODE_SOFTENING
ADAPTIVE_HYDRO_SOFTENING
TREE_BASED_TIMESTEPS

REGULARIZE_MESH_CM_DRIFT
REGULARIZE_MESH_CM_DRIFT_USE_SOUNDSPEED

DOUBLEPRECISION=1
DOUBLEPRECISION_FFTW
INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
OUTPUT_COORDINATES_IN_DOUBLEPRECISION
NGB_TREE_DOUBLEPRECISION

HAVE_HDF5
COOLING

BLACKHOLE_FFR
BH_FFR_SEED_ONLY_MOST_MASSIVE

FOF
FOF_PRIMARY_LINK_TYPES=2
FOF_SECONDARY_LINK_TYPES=1+32

GENERATE_GAS_IN_ICS

PROCESS_TIMES_OF_OUTPUTLIST
REDUCE_FLUSH
