#!/bin/bash

# FFR-MACER Iteration-4.5 cosmological seed smoke test.
# Deliberately separate from the production Config_FFR_MACER.sh.

SELFGRAVITY

PMGRID=128
RCUT=5.0

NSOFTTYPES=2
MULTIPLE_NODE_SOFTENING
ADAPTIVE_HYDRO_SOFTENING

TREE_BASED_TIMESTEPS

REGULARIZE_MESH_CM_DRIFT
REGULARIZE_MESH_CM_DRIFT_USE_SOUNDSPEED

DOUBLEPRECISION=1
DOUBLEPRECISION_FFTW
OUTPUT_COORDINATES_IN_DOUBLEPRECISION
NGB_TREE_DOUBLEPRECISION

HAVE_HDF5

BLACKHOLE_FFR

FOF
FOF_PRIMARY_LINK_TYPES=2
FOF_SECONDARY_LINK_TYPES=1+32

# MUSIC2 writes a DM-only unigrid. AREPO splits each Type-1 particle into
# Type-0 gas + Type-1 dark matter using OmegaBaryon/Omega0.
GENERATE_GAS_IN_ICS

PROCESS_TIMES_OF_OUTPUTLIST
REDUCE_FLUSH
