#!/usr/bin/env python3
"""Generate parameter files for the nested high-resolution reference runs."""
from __future__ import annotations

import json
import math
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
FLOW = HERE.parent
sys.path.insert(0, str(FLOW))

import generate_run_files as R


TRUTH_LEVELS = ("HR4", "HR5", "HR6")
NTASKS = {"HR4": 16, "HR5": 16, "HR6": 16}

PC_CM = 3.0856775814913673e18
KM_CM = 1.0e5

# The reference sink is deliberately much faster than the resolved inflow.
# Its convergence must still be checked; it is an absorbing boundary, not a
# physical accretion-timescale prescription.
ABSORBER_A = 100.0
ABSORBER_MAX_FRACTION = 0.50

FAMILIES = {
    "bhl": [
        ("M0p0", 0.0), ("M0p5", 0.5), ("M1p0", 1.0),
        ("M2p0", 2.0), ("M5p0", 5.0),
    ],
    "rotating": [
        ("f0p00", 0.0), ("f0p25", 0.25), ("f0p50", 0.5),
        ("f0p75", 0.75), ("f1p00", 1.0),
    ],
    "turbulent": [
        ("M0p5", 0.5), ("M1p0", 1.0), ("M2p0", 2.0), ("M5p0", 5.0),
    ],
}


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def bhl_reference_duration_myr(mach: float) -> tuple[float, float, float]:
    """Return (duration, R_BHL, t_BHL) in Myr/pc/Myr.

    Evolve for 1.5 characteristic crossing times of the BHL radius, with a
    0.25 Myr floor for the very fast/high-Mach cases.
    """
    cs = R.BHL_CS_KMS
    veff = cs * math.sqrt(1.0 + mach * mach)
    g_pc = 4.30091e-3
    mbh = 1.0e5
    r_bhl = 2.0 * g_pc * mbh / (veff * veff)
    t_bhl_s = r_bhl * PC_CM / (veff * KM_CM)
    t_bhl_myr = t_bhl_s / R.SEC_PER_MYR
    return max(1.5 * t_bhl_myr, 0.25), r_bhl, t_bhl_myr


def duration_for_case(family: str, value: float) -> tuple[float, dict]:
    if family == "bhl":
        duration, r_bhl, t_bhl = bhl_reference_duration_myr(value)
        return duration, {"r_bhl_pc": r_bhl, "t_bhl_myr": t_bhl}
    # The supplied rotating/turbulent flow needs time for gas initially around
    # R_acc to reach the central absorber.  Three Myr is longer than the
    # ~1.5--2 Myr radial/free-fall time around 12.5 pc in these ICs.
    return 3.0, {}


def output_list(times_code: list[float]) -> str:
    return "".join(f"{t:.17g} 2\n" for t in times_code)


def reference_parameter_text(
    *,
    init_stem: str,
    output_dir: str,
    output_list_file: str,
    time_max: float,
    sink_radius_kpc: float,
) -> str:
    max_step = time_max / 500.0
    statistics_step = time_max / 100.0

    text = R.parameter_text(
        init_stem=init_stem,
        output_dir=output_dir,
        output_list_file=output_list_file,
        time_max=time_max,
        max_step=max_step,
        statistics_step=statistics_step,
    )

    replacements = {
        "% Controlled non-cosmological BH accretion-flow benchmark.":
            "% High-resolution numerical-reference BH accretion run.",
        "% Generated by generate_run_files.py. Do not hand-edit generated files.":
            "% Generated by reference_truth/generate_reference_runs.py. Do not hand-edit.",
        "% Passive comparison: selected shell-FFR sink is Eddington-suppressed;":
            "% Tiny rapidly draining absorber; the converged realized rate is the reference.",
        "% compare the five BH_BENCHMARK_ALL raw estimators.":
            "% No feedback; absorber-rate and spatial-resolution convergence are required.",
        "SofteningComovingType1                  0.0002":
            "SofteningComovingType1                  0.00002",
        "SofteningMaxPhysType1                   0.0002":
            "SofteningMaxPhysType1                   0.00002",
        "BHAccretionRadius                       0.0125":
            f"BHAccretionRadius                       {sink_radius_kpc:.17g}",
        "BHFeedbackRadius                        0.025":
            f"BHFeedbackRadius                        {2.0 * sink_radius_kpc:.17g}",
        "BHFreeFallA                             1.0e-3":
            f"BHFreeFallA                             {ABSORBER_A:.17g}",
        "BHMaxSinkFraction                       0.25":
            f"BHMaxSinkFraction                       {ABSORBER_MAX_FRACTION:.17g}",
        "BHBenchmarkAccretionModel               4":
            "BHBenchmarkAccretionModel               3",
        "BHBenchmarkEddingtonFactor              1.0e-8":
            "BHBenchmarkEddingtonFactor              1.0e30",
    }

    for old, new in replacements.items():
        if old not in text:
            raise RuntimeError(f"expected parameter template text not found: {old}")
        text = text.replace(old, new)

    return text


def main() -> None:
    ic_manifest_path = HERE / "reference_ic_manifest.json"
    if not ic_manifest_path.exists():
        raise SystemExit(
            "Missing reference_ic_manifest.json. Run "
            "python3 reference_truth/generate_reference_ics.py first."
        )

    ic_manifest = json.loads(ic_manifest_path.read_text())["ics"]
    by_key = {(x["family"], x["tag"], x["level"]): x for x in ic_manifest}

    manifest: list[dict] = []

    for family, cases in FAMILIES.items():
        for tag, value in cases:
            end_myr, extras = duration_for_case(family, value)
            tmax = end_myr * R.CODE_PER_MYR

            # Twenty snapshots from 5% through 100%; the analyzer uses late-time
            # cumulative sink growth to estimate the reference rate.
            output_rel = f"reference_truth/common/outputlists/{family}_{tag}.txt"
            write(
                FLOW / output_rel,
                output_list([tmax * i / 20.0 for i in range(1, 21)]),
            )

            for level in TRUTH_LEVELS:
                key = (family, tag, level)
                if key not in by_key:
                    raise RuntimeError(f"missing reference IC manifest entry {key}")

                ic = by_key[key]
                sink_pc = float(ic["recommended_sink_radius_pc"])
                sink_kpc = sink_pc / 1000.0
                stem = f"truth_{family}_{tag}_{level}"

                init_stem = str(Path(ic["ic"]).with_suffix(""))
                param_rel = f"reference_truth/{family}/params/{level}/{stem}.txt"
                out_rel = f"reference_truth/{family}/outputs/{level}/{stem}"
                log_rel = f"reference_truth/{family}/logs/{level}/{stem}.log"

                write(
                    FLOW / param_rel,
                    reference_parameter_text(
                        init_stem=init_stem,
                        output_dir=out_rel,
                        output_list_file=output_rel,
                        time_max=tmax,
                        sink_radius_kpc=sink_kpc,
                    ),
                )

                manifest.append({
                    "family": family,
                    "tag": tag,
                    "control_value": value,
                    "level": level,
                    "end_myr": end_myr,
                    "time_max_code": tmax,
                    "finest_dx_pc": ic["finest_dx_pc"],
                    "sink_radius_pc": sink_pc,
                    "absorber_A": ABSORBER_A,
                    "absorber_max_fraction": ABSORBER_MAX_FRACTION,
                    "parameter_file": param_rel,
                    "output_list": output_rel,
                    "output_dir": out_rel,
                    "log_file": log_rel,
                    "recommended_ntasks": NTASKS[level],
                    **extras,
                })

    out = HERE / "reference_run_manifest.json"
    out.write_text(json.dumps({"runs": manifest}, indent=2, sort_keys=True) + "\n")

    print(f"Generated {len(manifest)} high-resolution reference parameter files")
    print("  physical cases: 14")
    print("  reference levels per case: HR4, HR5, HR6")
    print(f"  absorber A={ABSORBER_A:g}, max fraction/active step={ABSORBER_MAX_FRACTION:g}")
    print(f"Wrote {out.relative_to(FLOW)}")


if __name__ == "__main__":
    main()
