#!/usr/bin/env python3
from __future__ import annotations

import json
import math
from pathlib import Path

HERE = Path(__file__).resolve().parent

# Code units used by the IC generator and parameter files.
UNIT_LENGTH_CGS = 3.085678e21       # 1 kpc
UNIT_MASS_CGS = 1.989e43            # 1e10 Msun
UNIT_VELOCITY_CGS = 1.0e5           # 1 km/s
SEC_PER_MYR = 1.0e6 * 365.25 * 86400.0
MYR_PER_CODE = (UNIT_LENGTH_CGS / UNIT_VELOCITY_CGS) / SEC_PER_MYR
CODE_PER_MYR = 1.0 / MYR_PER_CODE

R_ACC_PC = 12.5
BOX_PC = 100.0
BHL_CS_KMS = 5.0

LEVELS = ("L0", "L1", "L2")
NTASKS = {"L0": 2, "L1": 4, "L2": 16}

FAMILIES = {
    "bhl": [
        ("M0p0", 0.0), ("M0p5", 0.5), ("M1p0", 1.0),
        ("M2p0", 2.0), ("M5p0", 5.0),
    ],
    "rotating": [
        ("f0p00", 0.0), ("f0p25", 0.25), ("f0p50", 0.5),
        ("f0p75", 0.75), ("f1p00", 1.0),
    ],
    "turbulent": [
        ("M0p5", 0.5), ("M1p0", 1.0), ("M2p0", 2.0), ("M5p0", 5.0),
    ],
}

REPRESENTATIVE = {
    "bhl": {"M0p5", "M2p0", "M5p0"},
    "rotating": {"f0p25", "f0p75", "f1p00"},
    "turbulent": {"M0p5", "M2p0", "M5p0"},
}


def stem(family: str, tag: str, level: str) -> str:
    if family == "bhl":
        return f"bhl_{tag}_{level}"
    if family == "rotating":
        return f"rot_{tag}_{level}"
    if family == "turbulent":
        return f"turb_{tag}_{level}"
    raise ValueError(family)


def ic_relpath(family: str, tag: str, level: str) -> str:
    return f"{family}/ics/{level}/{stem(family, tag, level)}"


def bhl_tacc_myr(mach: float) -> float:
    # t_acc = R_acc / sqrt(cs^2 + v_inf^2).
    pc_km = 3.0856775814913673e13
    v_eff = BHL_CS_KMS * math.sqrt(1.0 + mach * mach)
    return (R_ACC_PC * pc_km / v_eff) / SEC_PER_MYR


def output_list(times_code: list[float]) -> str:
    # DumpFlag=2 writes the full snapshot but deliberately skips FoF.
    return "".join(f"{t:.17g} 2\n" for t in times_code)


def parameter_text(*, init_stem: str, output_dir: str, output_list_file: str,
                   time_max: float, max_step: float, statistics_step: float) -> str:
    return f"""% Controlled non-cosmological BH accretion-flow benchmark.
% Generated by generate_run_files.py. Do not hand-edit generated files.
% Passive comparison: selected shell-FFR sink is Eddington-suppressed;
% compare the five BH_BENCHMARK_ALL raw estimators.

%---- Files
InitCondFile                            {init_stem}
OutputDir                               {output_dir}
SnapshotFileBase                        snap
OutputListFilename                      {output_list_file}

%---- Formats
ICFormat                                3
SnapFormat                              3

%---- CPU / restart
TimeLimitCPU                            172800
CpuTimeBetRestartFile                   1.0e30
FlushCpuTimeDiff                        120
ResubmitOn                              0
ResubmitCommand                         none

%---- Memory per MPI rank [MB]
MaxMemSize                              1500

%---- Non-cosmological interval
TimeBegin                               0.0
TimeMax                                 {time_max:.17g}

ComovingIntegrationOn                   0
PeriodicBoundariesOn                    1
CoolingOn                               0
StarformationOn                         0

Omega0                                  0.0
OmegaLambda                             0.0
OmegaBaryon                             0.0
HubbleParam                             1.0
BoxSize                                 0.1

%---- Outputs
OutputListOn                            1
TimeBetSnapshot                         1.0
TimeOfFirstSnapshot                     1.0
TimeBetStatistics                       {statistics_step:.17g}
NumFilesPerSnapshot                     1
NumFilesWrittenInParallel               1

%---- Time integration
TypeOfTimestepCriterion                 0
ErrTolIntAccuracy                       0.012
CourantFac                              0.3
MaxSizeTimestep                         {max_step:.17g}
MinSizeTimestep                         1.0e-12

%---- Gas initialization / floors
% InternalEnergy is present in every HDF5 IC; InitGasTemp is only a fallback.
InitGasTemp                             100.0
MinGasTemp                              1.0
MinimumDensityOnStartUp                 1.0e-20
LimitUBelowThisDensity                  0.0
LimitUBelowCertainDensityToThisValue    0.0
MinEgySpec                              0.0

%---- Gravity / domain
TypeOfOpeningCriterion                  1
ErrTolTheta                             0.7
ErrTolForceAcc                          0.0025
MultipleDomains                         4
TopNodeFactor                           2.5
ActivePartFracForNewDomainDecomp        0.01

%---- Initial gas density estimate
DesNumNgb                               64
MaxNumNgbDeviation                      4

%---- Units: kpc, 1e10 Msun, km/s
UnitLength_in_cm                        3.085678e21
UnitMass_in_g                           1.989e43
UnitVelocity_in_cm_per_s                1.0e5
GravityConstantInternal                 0

%---- Gravity softenings [kpc; non-cosmological]
SofteningComovingType0                  0.0002
SofteningComovingType1                  0.0002
SofteningMaxPhysType0                   0.0002
SofteningMaxPhysType1                   0.0002
GasSoftFactor                           2.5
SofteningTypeOfPartType0                0
SofteningTypeOfPartType1                1
SofteningTypeOfPartType2                1
SofteningTypeOfPartType3                1
SofteningTypeOfPartType4                1
SofteningTypeOfPartType5                1
MinimumComovingHydroSoftening           0.00005
AdaptiveHydroSofteningSpacing           1.2

%---- Moving-mesh regularization
CellShapingSpeed                        0.5
CellShapingFactor                       1.0

%---- Fixed physical apertures
BHAccretionRadius                       0.0125
BHFeedbackRadius                        0.025

%---- FoF seeding parameters (dormant because ComovingIntegrationOn=0)
BHSeedHaloMassMsun                      2.0e6
BHSeedMassMsun                          1.0e5
BHSeedMinRedshift                       100.0
BHSeedMaxDonorFraction                  0.5

%---- Resolved FFR capture
BHFreeFallA                             1.0e-3
BHFreeFallAlpha                         0.0
BHUseFullCentralMass                    1
BHMaxSinkFraction                       0.25

%---- Reservoir/MACER parameters (not exercised by direct+NONE runs)
BHDiskTimeMyr                           42.0
BHDiskTimeExponent                      0.4
BHRHotMaxInRs                           1200.0
BHRadiativeEfficiency                   0.1
BHWindBurstFactor                       0.01
BHJetBurstFactor                        0.10
BHUseCentralBindingTerm                 1
BHWindConeAngleDeg                      45.0
BHJetConeAngleDeg                       15.0
BHMinCoherence                          0.30
BHJetDirectionTimeFactor                1.0
BHMinTargetsPerLobe                     8
BHMinActiveTargetMassFrac               0.5
BHMaxPacketsPerStep                     4
BHDMNeighbours                          2
BHInternalTimestepFactor                1.0e30

%---- Benchmark accretion
% The selected model only supplies the negligible passive sink.
% BH_BENCHMARK_ALL reports all five RAW estimators from the same environment.
BHBenchmarkAccretionModel               4
BHBenchmarkAccretionTarget              1
BHBenchmarkBoostMode                    1
BHBenchmarkBoostAlpha                   100.0
BHBenchmarkBoostDensityThreshold        0.1
BHBenchmarkBoostBeta                    2.0
BHBenchmarkAMViscosity                  6.283185307179586
BHBenchmarkRadiativeEfficiency          0.2
BHBenchmarkEddingtonFactor              1.0e-8

%---- Benchmark feedback
BHBenchmarkFeedbackModel                0
BHBenchmarkTNGChi0                      0.002
BHBenchmarkTNGChiBeta                   2.0
BHBenchmarkTNGChiMax                     0.1
BHBenchmarkTNGThermalCoupling            0.1
BHBenchmarkTNGKineticMaxEfficiency       0.2
BHBenchmarkTNGKineticDensityFactor       0.05
BHBenchmarkTNGSFThresholdNH              0.1065
BHBenchmarkTNGKineticBurstFactor         20.0
"""


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def add_run(manifest: list[dict], *, family: str, tag: str, value: float,
            level: str, stage: str, end_myr: float, output_key: str) -> None:
    s = stem(family, tag, level)
    suffix = "diag" if stage == "diagnostic" else "evolve"
    param_rel = f"{family}/params/{s}_{suffix}.txt"
    out_rel = f"{family}/outputs/{suffix}/{s}"
    log_rel = f"{family}/logs/{suffix}/{s}.log"
    outputlist_rel = f"common/outputlists/{output_key}.txt"
    tmax = end_myr * CODE_PER_MYR

    # Diagnostic runs need only ~10 ceiling steps. Evolved runs use <=1% of
    # the intended physical duration; hydro/gravity criteria may reduce this.
    max_step = tmax / (10.0 if stage == "diagnostic" else 100.0)
    stats_step = max_step * 5.0

    write(HERE / param_rel, parameter_text(
        init_stem=ic_relpath(family, tag, level),
        output_dir=out_rel,
        output_list_file=outputlist_rel,
        time_max=tmax,
        max_step=max_step,
        statistics_step=stats_step,
    ))

    manifest.append({
        "family": family,
        "tag": tag,
        "control_value": value,
        "level": level,
        "stage": stage,
        "end_myr": end_myr,
        "time_max_code": tmax,
        "max_timestep_code": max_step,
        "parameter_file": param_rel,
        "output_list": outputlist_rel,
        "output_dir": out_rel,
        "log_file": log_rel,
        "recommended_ntasks": NTASKS[level],
        "selected_sink_model": "ffr-shell",
        "selected_sink_model_id": 4,
        "accretion_target": "direct",
        "feedback": "none",
        "eddington_factor": 1.0e-8,
    })


def main() -> None:
    # Shared output lists. Flag=2 is essential: it writes a full snapshot while
    # preventing the compiled FoF module from trying to build a DM catalogue.
    diag_end_myr = 0.001  # 1 kyr
    diag_end = diag_end_myr * CODE_PER_MYR
    write(HERE / "common/outputlists/diag_1kyr.txt", output_list([diag_end]))

    short_end_myr = 0.2   # 200 kyr perturbative rotation/turbulence evolution
    short_end = short_end_myr * CODE_PER_MYR
    write(HERE / "common/outputlists/evolve_200kyr.txt",
          output_list([short_end * f for f in (0.25, 0.50, 0.75, 1.0)]))

    bhl_end = {}
    for tag, mach in FAMILIES["bhl"]:
        if tag not in REPRESENTATIVE["bhl"]:
            continue
        end_myr = bhl_tacc_myr(mach)
        end_code = end_myr * CODE_PER_MYR
        key = f"evolve_bhl_{tag}"
        bhl_end[tag] = (end_myr, key)
        write(HERE / f"common/outputlists/{key}.txt",
              output_list([end_code * f for f in (0.25, 0.50, 0.75, 1.0)]))

    manifest: list[dict] = []

    # Stage B: exactly one passive startup run for every IC.
    for family, controls in FAMILIES.items():
        for tag, value in controls:
            for level in LEVELS:
                add_run(manifest, family=family, tag=tag, value=value,
                        level=level, stage="diagnostic",
                        end_myr=diag_end_myr, output_key="diag_1kyr")

    # Stage D: representative L1/L2 passive evolved-flow subset.
    for family, controls in FAMILIES.items():
        for tag, value in controls:
            if tag not in REPRESENTATIVE[family]:
                continue
            for level in ("L1", "L2"):
                if family == "bhl":
                    end_myr, key = bhl_end[tag]
                else:
                    end_myr, key = short_end_myr, "evolve_200kyr"
                add_run(manifest, family=family, tag=tag, value=value,
                        level=level, stage="evolved",
                        end_myr=end_myr, output_key=key)

    data = {
        "schema_version": 1,
        "myr_per_code_time": MYR_PER_CODE,
        "code_time_per_myr": CODE_PER_MYR,
        "diagnostic_count": sum(r["stage"] == "diagnostic" for r in manifest),
        "evolved_count": sum(r["stage"] == "evolved" for r in manifest),
        "total_count": len(manifest),
        "runs": manifest,
    }
    write(HERE / "run_manifest.json", json.dumps(data, indent=2, sort_keys=True) + "\n")

    print(f"Generated {data['diagnostic_count']} diagnostic parameter files")
    print(f"Generated {data['evolved_count']} representative evolved parameter files")
    print(f"Total planned runs: {data['total_count']}")
    print(f"1 code-time unit = {MYR_PER_CODE:.12g} Myr")
    for tag in sorted(bhl_end):
        print(f"BHL {tag}: t_end=t_acc={bhl_end[tag][0]:.9g} Myr")


if __name__ == "__main__":
    main()